package cn.edu.hist.mapper;

import cn.edu.hist.model.BssSysSystem;

public interface BssSysSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int insert(BssSysSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int insertSelective(BssSysSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    BssSysSystem selectByPrimaryKey(String sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BssSysSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BssSysSystem record);
}