package cn.edu.hist.mapper;

import cn.edu.hist.model.BssSysArea;

public interface BssSysAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_area
     *
     * @mbggenerated
     */
    int insert(BssSysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_area
     *
     * @mbggenerated
     */
    int insertSelective(BssSysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_area
     *
     * @mbggenerated
     */
    BssSysArea selectByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BssSysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BssSysArea record);
}