package cn.edu.hist.mapper;

import cn.edu.hist.model.BssSysSystem;
import cn.edu.hist.model.BssSysSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BssSysSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int countByExample(BssSysSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int deleteByExample(BssSysSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int insert(BssSysSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int insertSelective(BssSysSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    List<BssSysSystem> selectByExample(BssSysSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    BssSysSystem selectByPrimaryKey(String sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BssSysSystem record, @Param("example") BssSysSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BssSysSystem record, @Param("example") BssSysSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BssSysSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_system
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BssSysSystem record);
}