package cn.edu.hist.mapper;

import cn.edu.hist.model.BssSysOperate;
import cn.edu.hist.model.BssSysOperateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BssSysOperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int countByExample(BssSysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int deleteByExample(BssSysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String operateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int insert(BssSysOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int insertSelective(BssSysOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    List<BssSysOperate> selectByExample(BssSysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    BssSysOperate selectByPrimaryKey(String operateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BssSysOperate record, @Param("example") BssSysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BssSysOperate record, @Param("example") BssSysOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BssSysOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bss_sys_operate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BssSysOperate record);
}