package cn.edu.hist.mapper;

import cn.edu.hist.model.ErrorTaskBackup;
import cn.edu.hist.model.ErrorTaskBackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorTaskBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    int countByExample(ErrorTaskBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    int deleteByExample(ErrorTaskBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    int insert(ErrorTaskBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    int insertSelective(ErrorTaskBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    List<ErrorTaskBackup> selectByExample(ErrorTaskBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ErrorTaskBackup record, @Param("example") ErrorTaskBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_task_backup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ErrorTaskBackup record, @Param("example") ErrorTaskBackupExample example);
}