package cn.edu.hist.mapper;

import cn.edu.hist.model.Gysypml;

public interface GysypmlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gysypml
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gysypml
     *
     * @mbggenerated
     */
    int insert(Gysypml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gysypml
     *
     * @mbggenerated
     */
    int insertSelective(Gysypml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gysypml
     *
     * @mbggenerated
     */
    Gysypml selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gysypml
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gysypml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gysypml
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Gysypml record);
}