package cn.edu.hist.mapper;

import cn.edu.hist.model.Userrole;
import org.apache.ibatis.annotations.Param;

public interface UserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userid") String userid, @Param("userrole") String userrole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int insert(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int insertSelective(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    Userrole selectByPrimaryKey(@Param("userid") String userid, @Param("userrole") String userrole);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userrole record);
}