package cn.edu.hist.mapper;

import cn.edu.hist.model.Userjd;
import cn.edu.hist.model.UserjdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserjdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int countByExample(UserjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int deleteByExample(UserjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int insert(Userjd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int insertSelective(Userjd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    List<Userjd> selectByExample(UserjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    Userjd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Userjd record, @Param("example") UserjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Userjd record, @Param("example") UserjdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userjd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userjd
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userjd record);
}