package cn.edu.hist.mapper;

import cn.edu.hist.model.YpxxBackup;
import cn.edu.hist.model.YpxxBackupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YpxxBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int countByExample(YpxxBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int deleteByExample(YpxxBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int insert(YpxxBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int insertSelective(YpxxBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    List<YpxxBackup> selectByExample(YpxxBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YpxxBackup record, @Param("example") YpxxBackupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YpxxBackup record, @Param("example") YpxxBackupExample example);
}