package cn.edu.hist.mapper;

import cn.edu.hist.model.YpxxBackup;

public interface YpxxBackupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int insert(YpxxBackup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ypxx_backup
     *
     * @mbggenerated
     */
    int insertSelective(YpxxBackup record);
}