package cn.edu.hist.mapper;

import cn.edu.hist.model.Yycgdmx2014;

public interface Yycgdmx2014Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdmx2014
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdmx2014
     *
     * @mbggenerated
     */
    int insert(Yycgdmx2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdmx2014
     *
     * @mbggenerated
     */
    int insertSelective(Yycgdmx2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdmx2014
     *
     * @mbggenerated
     */
    Yycgdmx2014 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdmx2014
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yycgdmx2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdmx2014
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yycgdmx2014 record);
}