package cn.edu.hist.mapper;

import cn.edu.hist.model.Yycgdrk2014;

public interface Yycgdrk2014Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdrk2014
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdrk2014
     *
     * @mbggenerated
     */
    int insert(Yycgdrk2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdrk2014
     *
     * @mbggenerated
     */
    int insertSelective(Yycgdrk2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdrk2014
     *
     * @mbggenerated
     */
    Yycgdrk2014 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdrk2014
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yycgdrk2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yycgdrk2014
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yycgdrk2014 record);
}