package cn.edu.hist.mapper;

import cn.edu.hist.model.Yyjsdmx2014;
import cn.edu.hist.model.Yyjsdmx2014Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Yyjsdmx2014Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int countByExample(Yyjsdmx2014Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int deleteByExample(Yyjsdmx2014Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int insert(Yyjsdmx2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int insertSelective(Yyjsdmx2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    List<Yyjsdmx2014> selectByExample(Yyjsdmx2014Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    Yyjsdmx2014 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Yyjsdmx2014 record, @Param("example") Yyjsdmx2014Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Yyjsdmx2014 record, @Param("example") Yyjsdmx2014Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yyjsdmx2014 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyjsdmx2014
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yyjsdmx2014 record);
}