package cn.edu.hist.mapper;

import cn.edu.hist.model.Yythdmx;

public interface YythdmxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yythdmx
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yythdmx
     *
     * @mbggenerated
     */
    int insert(Yythdmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yythdmx
     *
     * @mbggenerated
     */
    int insertSelective(Yythdmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yythdmx
     *
     * @mbggenerated
     */
    Yythdmx selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yythdmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yythdmx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yythdmx
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yythdmx record);
}