package cn.edu.hist.mapper;

import cn.edu.hist.model.Yyypml;
import cn.edu.hist.model.YyypmlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyypmlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int countByExample(YyypmlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int deleteByExample(YyypmlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int insert(Yyypml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int insertSelective(Yyypml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    List<Yyypml> selectByExample(YyypmlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    Yyypml selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Yyypml record, @Param("example") YyypmlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Yyypml record, @Param("example") YyypmlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Yyypml record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyypml
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Yyypml record);
}