package cn.edu.hist.model;

public class BssSysRoleoperate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.ROID
     *
     * @mbggenerated
     */
    private String roid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.RMID
     *
     * @mbggenerated
     */
    private String rmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.OPERATEID
     *
     * @mbggenerated
     */
    private String operateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_roleoperate.VCHAR4
     *
     * @mbggenerated
     */
    private String vchar4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.ROID
     *
     * @return the value of bss_sys_roleoperate.ROID
     *
     * @mbggenerated
     */
    public String getRoid() {
        return roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.ROID
     *
     * @param roid the value for bss_sys_roleoperate.ROID
     *
     * @mbggenerated
     */
    public void setRoid(String roid) {
        this.roid = roid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.RMID
     *
     * @return the value of bss_sys_roleoperate.RMID
     *
     * @mbggenerated
     */
    public String getRmid() {
        return rmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.RMID
     *
     * @param rmid the value for bss_sys_roleoperate.RMID
     *
     * @mbggenerated
     */
    public void setRmid(String rmid) {
        this.rmid = rmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.OPERATEID
     *
     * @return the value of bss_sys_roleoperate.OPERATEID
     *
     * @mbggenerated
     */
    public String getOperateid() {
        return operateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.OPERATEID
     *
     * @param operateid the value for bss_sys_roleoperate.OPERATEID
     *
     * @mbggenerated
     */
    public void setOperateid(String operateid) {
        this.operateid = operateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.VCHAR1
     *
     * @return the value of bss_sys_roleoperate.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.VCHAR1
     *
     * @param vchar1 the value for bss_sys_roleoperate.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.VCHAR2
     *
     * @return the value of bss_sys_roleoperate.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.VCHAR2
     *
     * @param vchar2 the value for bss_sys_roleoperate.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.VCHAR3
     *
     * @return the value of bss_sys_roleoperate.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.VCHAR3
     *
     * @param vchar3 the value for bss_sys_roleoperate.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_roleoperate.VCHAR4
     *
     * @return the value of bss_sys_roleoperate.VCHAR4
     *
     * @mbggenerated
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_roleoperate.VCHAR4
     *
     * @param vchar4 the value for bss_sys_roleoperate.VCHAR4
     *
     * @mbggenerated
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4;
    }
}