package cn.edu.hist.model;

public class BssSysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.LOGID
     *
     * @mbggenerated
     */
    private String logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.TRUENAME
     *
     * @mbggenerated
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.CLIENTIP
     *
     * @mbggenerated
     */
    private String clientip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.OPERTYPE
     *
     * @mbggenerated
     */
    private String opertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.MODULENAME
     *
     * @mbggenerated
     */
    private String modulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.OPERCONTENT
     *
     * @mbggenerated
     */
    private String opercontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.OPERDATE
     *
     * @mbggenerated
     */
    private String operdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.VCHAR4
     *
     * @mbggenerated
     */
    private String vchar4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.VCHAR5
     *
     * @mbggenerated
     */
    private String vchar5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bss_sys_log.VCHAR6
     *
     * @mbggenerated
     */
    private String vchar6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.LOGID
     *
     * @return the value of bss_sys_log.LOGID
     *
     * @mbggenerated
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.LOGID
     *
     * @param logid the value for bss_sys_log.LOGID
     *
     * @mbggenerated
     */
    public void setLogid(String logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.USERNAME
     *
     * @return the value of bss_sys_log.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.USERNAME
     *
     * @param username the value for bss_sys_log.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.TRUENAME
     *
     * @return the value of bss_sys_log.TRUENAME
     *
     * @mbggenerated
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.TRUENAME
     *
     * @param truename the value for bss_sys_log.TRUENAME
     *
     * @mbggenerated
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.CLIENTIP
     *
     * @return the value of bss_sys_log.CLIENTIP
     *
     * @mbggenerated
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.CLIENTIP
     *
     * @param clientip the value for bss_sys_log.CLIENTIP
     *
     * @mbggenerated
     */
    public void setClientip(String clientip) {
        this.clientip = clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.OPERTYPE
     *
     * @return the value of bss_sys_log.OPERTYPE
     *
     * @mbggenerated
     */
    public String getOpertype() {
        return opertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.OPERTYPE
     *
     * @param opertype the value for bss_sys_log.OPERTYPE
     *
     * @mbggenerated
     */
    public void setOpertype(String opertype) {
        this.opertype = opertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.MODULENAME
     *
     * @return the value of bss_sys_log.MODULENAME
     *
     * @mbggenerated
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.MODULENAME
     *
     * @param modulename the value for bss_sys_log.MODULENAME
     *
     * @mbggenerated
     */
    public void setModulename(String modulename) {
        this.modulename = modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.OPERCONTENT
     *
     * @return the value of bss_sys_log.OPERCONTENT
     *
     * @mbggenerated
     */
    public String getOpercontent() {
        return opercontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.OPERCONTENT
     *
     * @param opercontent the value for bss_sys_log.OPERCONTENT
     *
     * @mbggenerated
     */
    public void setOpercontent(String opercontent) {
        this.opercontent = opercontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.OPERDATE
     *
     * @return the value of bss_sys_log.OPERDATE
     *
     * @mbggenerated
     */
    public String getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.OPERDATE
     *
     * @param operdate the value for bss_sys_log.OPERDATE
     *
     * @mbggenerated
     */
    public void setOperdate(String operdate) {
        this.operdate = operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.VCHAR1
     *
     * @return the value of bss_sys_log.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.VCHAR1
     *
     * @param vchar1 the value for bss_sys_log.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.VCHAR2
     *
     * @return the value of bss_sys_log.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.VCHAR2
     *
     * @param vchar2 the value for bss_sys_log.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.VCHAR3
     *
     * @return the value of bss_sys_log.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.VCHAR3
     *
     * @param vchar3 the value for bss_sys_log.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.VCHAR4
     *
     * @return the value of bss_sys_log.VCHAR4
     *
     * @mbggenerated
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.VCHAR4
     *
     * @param vchar4 the value for bss_sys_log.VCHAR4
     *
     * @mbggenerated
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.VCHAR5
     *
     * @return the value of bss_sys_log.VCHAR5
     *
     * @mbggenerated
     */
    public String getVchar5() {
        return vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.VCHAR5
     *
     * @param vchar5 the value for bss_sys_log.VCHAR5
     *
     * @mbggenerated
     */
    public void setVchar5(String vchar5) {
        this.vchar5 = vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bss_sys_log.VCHAR6
     *
     * @return the value of bss_sys_log.VCHAR6
     *
     * @mbggenerated
     */
    public String getVchar6() {
        return vchar6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bss_sys_log.VCHAR6
     *
     * @param vchar6 the value for bss_sys_log.VCHAR6
     *
     * @mbggenerated
     */
    public void setVchar6(String vchar6) {
        this.vchar6 = vchar6;
    }
}