package cn.edu.hist.model;

public class Dicttype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicttype.TYPECODE
     *
     * @mbggenerated
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicttype.TYPENAME
     *
     * @mbggenerated
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicttype.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicttype.TYPESORT
     *
     * @mbggenerated
     */
    private Integer typesort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dicttype.CODELENGTH
     *
     * @mbggenerated
     */
    private String codelength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicttype.TYPECODE
     *
     * @return the value of dicttype.TYPECODE
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicttype.TYPECODE
     *
     * @param typecode the value for dicttype.TYPECODE
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicttype.TYPENAME
     *
     * @return the value of dicttype.TYPENAME
     *
     * @mbggenerated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicttype.TYPENAME
     *
     * @param typename the value for dicttype.TYPENAME
     *
     * @mbggenerated
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicttype.REMARK
     *
     * @return the value of dicttype.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicttype.REMARK
     *
     * @param remark the value for dicttype.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicttype.TYPESORT
     *
     * @return the value of dicttype.TYPESORT
     *
     * @mbggenerated
     */
    public Integer getTypesort() {
        return typesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicttype.TYPESORT
     *
     * @param typesort the value for dicttype.TYPESORT
     *
     * @mbggenerated
     */
    public void setTypesort(Integer typesort) {
        this.typesort = typesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dicttype.CODELENGTH
     *
     * @return the value of dicttype.CODELENGTH
     *
     * @mbggenerated
     */
    public String getCodelength() {
        return codelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dicttype.CODELENGTH
     *
     * @param codelength the value for dicttype.CODELENGTH
     *
     * @mbggenerated
     */
    public void setCodelength(String codelength) {
        this.codelength = codelength;
    }
}