package cn.edu.hist.model;

public class ErrorTaskBackup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.TASKID
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.WSURL
     *
     * @mbggenerated
     */
    private String wsurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.WSMETHOD
     *
     * @mbggenerated
     */
    private String wsmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.WSNAMESPACE
     *
     * @mbggenerated
     */
    private String wsnamespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column error_task_backup.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.TASKID
     *
     * @return the value of error_task_backup.TASKID
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.TASKID
     *
     * @param taskid the value for error_task_backup.TASKID
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.WSURL
     *
     * @return the value of error_task_backup.WSURL
     *
     * @mbggenerated
     */
    public String getWsurl() {
        return wsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.WSURL
     *
     * @param wsurl the value for error_task_backup.WSURL
     *
     * @mbggenerated
     */
    public void setWsurl(String wsurl) {
        this.wsurl = wsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.WSMETHOD
     *
     * @return the value of error_task_backup.WSMETHOD
     *
     * @mbggenerated
     */
    public String getWsmethod() {
        return wsmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.WSMETHOD
     *
     * @param wsmethod the value for error_task_backup.WSMETHOD
     *
     * @mbggenerated
     */
    public void setWsmethod(String wsmethod) {
        this.wsmethod = wsmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.WSNAMESPACE
     *
     * @return the value of error_task_backup.WSNAMESPACE
     *
     * @mbggenerated
     */
    public String getWsnamespace() {
        return wsnamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.WSNAMESPACE
     *
     * @param wsnamespace the value for error_task_backup.WSNAMESPACE
     *
     * @mbggenerated
     */
    public void setWsnamespace(String wsnamespace) {
        this.wsnamespace = wsnamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.VCHAR1
     *
     * @return the value of error_task_backup.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.VCHAR1
     *
     * @param vchar1 the value for error_task_backup.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.VCHAR2
     *
     * @return the value of error_task_backup.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.VCHAR2
     *
     * @param vchar2 the value for error_task_backup.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column error_task_backup.VCHAR3
     *
     * @return the value of error_task_backup.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column error_task_backup.VCHAR3
     *
     * @param vchar3 the value for error_task_backup.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3;
    }
}