package cn.edu.hist.model;

public class Gysypml {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gysypml.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gysypml.YPXXID
     *
     * @mbggenerated
     */
    private String ypxxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gysypml.USERGYSID
     *
     * @mbggenerated
     */
    private String usergysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gysypml.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gysypml.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gysypml.ID
     *
     * @return the value of gysypml.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gysypml.ID
     *
     * @param id the value for gysypml.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gysypml.YPXXID
     *
     * @return the value of gysypml.YPXXID
     *
     * @mbggenerated
     */
    public String getYpxxid() {
        return ypxxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gysypml.YPXXID
     *
     * @param ypxxid the value for gysypml.YPXXID
     *
     * @mbggenerated
     */
    public void setYpxxid(String ypxxid) {
        this.ypxxid = ypxxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gysypml.USERGYSID
     *
     * @return the value of gysypml.USERGYSID
     *
     * @mbggenerated
     */
    public String getUsergysid() {
        return usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gysypml.USERGYSID
     *
     * @param usergysid the value for gysypml.USERGYSID
     *
     * @mbggenerated
     */
    public void setUsergysid(String usergysid) {
        this.usergysid = usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gysypml.VCHAR1
     *
     * @return the value of gysypml.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gysypml.VCHAR1
     *
     * @param vchar1 the value for gysypml.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gysypml.VCHAR2
     *
     * @return the value of gysypml.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gysypml.VCHAR2
     *
     * @param vchar2 the value for gysypml.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }
}