package cn.edu.hist.model;

import java.util.Date;

public class Syslog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.OPERATEDATE
     *
     * @mbggenerated
     */
    private Date operatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.USERIP
     *
     * @mbggenerated
     */
    private String userip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.LOGTYPE
     *
     * @mbggenerated
     */
    private String logtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syslog.MESSAGES
     *
     * @mbggenerated
     */
    private String messages;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.ID
     *
     * @return the value of syslog.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.ID
     *
     * @param id the value for syslog.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.USERID
     *
     * @return the value of syslog.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.USERID
     *
     * @param userid the value for syslog.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.OPERATEDATE
     *
     * @return the value of syslog.OPERATEDATE
     *
     * @mbggenerated
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.OPERATEDATE
     *
     * @param operatedate the value for syslog.OPERATEDATE
     *
     * @mbggenerated
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.USERIP
     *
     * @return the value of syslog.USERIP
     *
     * @mbggenerated
     */
    public String getUserip() {
        return userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.USERIP
     *
     * @param userip the value for syslog.USERIP
     *
     * @mbggenerated
     */
    public void setUserip(String userip) {
        this.userip = userip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.USERNAME
     *
     * @return the value of syslog.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.USERNAME
     *
     * @param username the value for syslog.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.LOGTYPE
     *
     * @return the value of syslog.LOGTYPE
     *
     * @mbggenerated
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.LOGTYPE
     *
     * @param logtype the value for syslog.LOGTYPE
     *
     * @mbggenerated
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syslog.MESSAGES
     *
     * @return the value of syslog.MESSAGES
     *
     * @mbggenerated
     */
    public String getMessages() {
        return messages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syslog.MESSAGES
     *
     * @param messages the value for syslog.MESSAGES
     *
     * @mbggenerated
     */
    public void setMessages(String messages) {
        this.messages = messages;
    }
}