package cn.edu.hist.model;

public class Sysrolemodule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrolemodule.ROLEID
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrolemodule.MODULEID
     *
     * @mbggenerated
     */
    private String moduleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrolemodule.ROLEID
     *
     * @return the value of sysrolemodule.ROLEID
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrolemodule.ROLEID
     *
     * @param roleid the value for sysrolemodule.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrolemodule.MODULEID
     *
     * @return the value of sysrolemodule.MODULEID
     *
     * @mbggenerated
     */
    public String getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrolemodule.MODULEID
     *
     * @param moduleid the value for sysrolemodule.MODULEID
     *
     * @mbggenerated
     */
    public void setModuleid(String moduleid) {
        this.moduleid = moduleid;
    }
}