package cn.edu.hist.model;

public class Userjd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.MC
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.DZ
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.YZBM
     *
     * @mbggenerated
     */
    private String yzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.XLR
     *
     * @mbggenerated
     */
    private String xlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.DH
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.CZ
     *
     * @mbggenerated
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.DZYX
     *
     * @mbggenerated
     */
    private String dzyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.WZ
     *
     * @mbggenerated
     */
    private String wz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userjd.DQ
     *
     * @mbggenerated
     */
    private String dq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.ID
     *
     * @return the value of userjd.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.ID
     *
     * @param id the value for userjd.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.MC
     *
     * @return the value of userjd.MC
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.MC
     *
     * @param mc the value for userjd.MC
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.DZ
     *
     * @return the value of userjd.DZ
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.DZ
     *
     * @param dz the value for userjd.DZ
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.YZBM
     *
     * @return the value of userjd.YZBM
     *
     * @mbggenerated
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.YZBM
     *
     * @param yzbm the value for userjd.YZBM
     *
     * @mbggenerated
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.XLR
     *
     * @return the value of userjd.XLR
     *
     * @mbggenerated
     */
    public String getXlr() {
        return xlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.XLR
     *
     * @param xlr the value for userjd.XLR
     *
     * @mbggenerated
     */
    public void setXlr(String xlr) {
        this.xlr = xlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.DH
     *
     * @return the value of userjd.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.DH
     *
     * @param dh the value for userjd.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.CZ
     *
     * @return the value of userjd.CZ
     *
     * @mbggenerated
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.CZ
     *
     * @param cz the value for userjd.CZ
     *
     * @mbggenerated
     */
    public void setCz(String cz) {
        this.cz = cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.DZYX
     *
     * @return the value of userjd.DZYX
     *
     * @mbggenerated
     */
    public String getDzyx() {
        return dzyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.DZYX
     *
     * @param dzyx the value for userjd.DZYX
     *
     * @mbggenerated
     */
    public void setDzyx(String dzyx) {
        this.dzyx = dzyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.WZ
     *
     * @return the value of userjd.WZ
     *
     * @mbggenerated
     */
    public String getWz() {
        return wz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.WZ
     *
     * @param wz the value for userjd.WZ
     *
     * @mbggenerated
     */
    public void setWz(String wz) {
        this.wz = wz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.VCHAR1
     *
     * @return the value of userjd.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.VCHAR1
     *
     * @param vchar1 the value for userjd.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.VCHAR2
     *
     * @return the value of userjd.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.VCHAR2
     *
     * @param vchar2 the value for userjd.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.VCHAR3
     *
     * @return the value of userjd.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.VCHAR3
     *
     * @param vchar3 the value for userjd.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userjd.DQ
     *
     * @return the value of userjd.DQ
     *
     * @mbggenerated
     */
    public String getDq() {
        return dq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userjd.DQ
     *
     * @param dq the value for userjd.DQ
     *
     * @mbggenerated
     */
    public void setDq(String dq) {
        this.dq = dq;
    }
}