package cn.edu.hist.model;

import java.util.Date;

public class YpxxBackup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.BM
     *
     * @mbggenerated
     */
    private String bm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.SCQYMC
     *
     * @mbggenerated
     */
    private String scqymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.SPMC
     *
     * @mbggenerated
     */
    private String spmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.ZBJG
     *
     * @mbggenerated
     */
    private Float zbjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.ZPDZ
     *
     * @mbggenerated
     */
    private String zpdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.PZWH
     *
     * @mbggenerated
     */
    private String pzwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.PZWHYXQ
     *
     * @mbggenerated
     */
    private Date pzwhyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.JKY
     *
     * @mbggenerated
     */
    private String jky;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.BZCZ
     *
     * @mbggenerated
     */
    private String bzcz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.BZDW
     *
     * @mbggenerated
     */
    private String bzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.LSJG
     *
     * @mbggenerated
     */
    private Float lsjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.LSJGCC
     *
     * @mbggenerated
     */
    private String lsjgcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.ZLCC
     *
     * @mbggenerated
     */
    private String zlcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.ZLCCSM
     *
     * @mbggenerated
     */
    private String zlccsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.YPJYBG
     *
     * @mbggenerated
     */
    private String ypjybg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.YPJYBGBM
     *
     * @mbggenerated
     */
    private String ypjybgbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.YPJYBGYXQ
     *
     * @mbggenerated
     */
    private Date ypjybgyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.JYZT
     *
     * @mbggenerated
     */
    private String jyzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.DW
     *
     * @mbggenerated
     */
    private String dw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.MC
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.JX
     *
     * @mbggenerated
     */
    private String jx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.GG
     *
     * @mbggenerated
     */
    private String gg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.ZHXS
     *
     * @mbggenerated
     */
    private String zhxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.PINYIN
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypxx_backup.LB
     *
     * @mbggenerated
     */
    private String lb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.ID
     *
     * @return the value of ypxx_backup.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.ID
     *
     * @param id the value for ypxx_backup.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.BM
     *
     * @return the value of ypxx_backup.BM
     *
     * @mbggenerated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.BM
     *
     * @param bm the value for ypxx_backup.BM
     *
     * @mbggenerated
     */
    public void setBm(String bm) {
        this.bm = bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.SCQYMC
     *
     * @return the value of ypxx_backup.SCQYMC
     *
     * @mbggenerated
     */
    public String getScqymc() {
        return scqymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.SCQYMC
     *
     * @param scqymc the value for ypxx_backup.SCQYMC
     *
     * @mbggenerated
     */
    public void setScqymc(String scqymc) {
        this.scqymc = scqymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.SPMC
     *
     * @return the value of ypxx_backup.SPMC
     *
     * @mbggenerated
     */
    public String getSpmc() {
        return spmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.SPMC
     *
     * @param spmc the value for ypxx_backup.SPMC
     *
     * @mbggenerated
     */
    public void setSpmc(String spmc) {
        this.spmc = spmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.ZBJG
     *
     * @return the value of ypxx_backup.ZBJG
     *
     * @mbggenerated
     */
    public Float getZbjg() {
        return zbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.ZBJG
     *
     * @param zbjg the value for ypxx_backup.ZBJG
     *
     * @mbggenerated
     */
    public void setZbjg(Float zbjg) {
        this.zbjg = zbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.ZPDZ
     *
     * @return the value of ypxx_backup.ZPDZ
     *
     * @mbggenerated
     */
    public String getZpdz() {
        return zpdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.ZPDZ
     *
     * @param zpdz the value for ypxx_backup.ZPDZ
     *
     * @mbggenerated
     */
    public void setZpdz(String zpdz) {
        this.zpdz = zpdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.PZWH
     *
     * @return the value of ypxx_backup.PZWH
     *
     * @mbggenerated
     */
    public String getPzwh() {
        return pzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.PZWH
     *
     * @param pzwh the value for ypxx_backup.PZWH
     *
     * @mbggenerated
     */
    public void setPzwh(String pzwh) {
        this.pzwh = pzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.PZWHYXQ
     *
     * @return the value of ypxx_backup.PZWHYXQ
     *
     * @mbggenerated
     */
    public Date getPzwhyxq() {
        return pzwhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.PZWHYXQ
     *
     * @param pzwhyxq the value for ypxx_backup.PZWHYXQ
     *
     * @mbggenerated
     */
    public void setPzwhyxq(Date pzwhyxq) {
        this.pzwhyxq = pzwhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.JKY
     *
     * @return the value of ypxx_backup.JKY
     *
     * @mbggenerated
     */
    public String getJky() {
        return jky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.JKY
     *
     * @param jky the value for ypxx_backup.JKY
     *
     * @mbggenerated
     */
    public void setJky(String jky) {
        this.jky = jky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.BZCZ
     *
     * @return the value of ypxx_backup.BZCZ
     *
     * @mbggenerated
     */
    public String getBzcz() {
        return bzcz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.BZCZ
     *
     * @param bzcz the value for ypxx_backup.BZCZ
     *
     * @mbggenerated
     */
    public void setBzcz(String bzcz) {
        this.bzcz = bzcz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.BZDW
     *
     * @return the value of ypxx_backup.BZDW
     *
     * @mbggenerated
     */
    public String getBzdw() {
        return bzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.BZDW
     *
     * @param bzdw the value for ypxx_backup.BZDW
     *
     * @mbggenerated
     */
    public void setBzdw(String bzdw) {
        this.bzdw = bzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.LSJG
     *
     * @return the value of ypxx_backup.LSJG
     *
     * @mbggenerated
     */
    public Float getLsjg() {
        return lsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.LSJG
     *
     * @param lsjg the value for ypxx_backup.LSJG
     *
     * @mbggenerated
     */
    public void setLsjg(Float lsjg) {
        this.lsjg = lsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.LSJGCC
     *
     * @return the value of ypxx_backup.LSJGCC
     *
     * @mbggenerated
     */
    public String getLsjgcc() {
        return lsjgcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.LSJGCC
     *
     * @param lsjgcc the value for ypxx_backup.LSJGCC
     *
     * @mbggenerated
     */
    public void setLsjgcc(String lsjgcc) {
        this.lsjgcc = lsjgcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.ZLCC
     *
     * @return the value of ypxx_backup.ZLCC
     *
     * @mbggenerated
     */
    public String getZlcc() {
        return zlcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.ZLCC
     *
     * @param zlcc the value for ypxx_backup.ZLCC
     *
     * @mbggenerated
     */
    public void setZlcc(String zlcc) {
        this.zlcc = zlcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.ZLCCSM
     *
     * @return the value of ypxx_backup.ZLCCSM
     *
     * @mbggenerated
     */
    public String getZlccsm() {
        return zlccsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.ZLCCSM
     *
     * @param zlccsm the value for ypxx_backup.ZLCCSM
     *
     * @mbggenerated
     */
    public void setZlccsm(String zlccsm) {
        this.zlccsm = zlccsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.YPJYBG
     *
     * @return the value of ypxx_backup.YPJYBG
     *
     * @mbggenerated
     */
    public String getYpjybg() {
        return ypjybg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.YPJYBG
     *
     * @param ypjybg the value for ypxx_backup.YPJYBG
     *
     * @mbggenerated
     */
    public void setYpjybg(String ypjybg) {
        this.ypjybg = ypjybg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.YPJYBGBM
     *
     * @return the value of ypxx_backup.YPJYBGBM
     *
     * @mbggenerated
     */
    public String getYpjybgbm() {
        return ypjybgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.YPJYBGBM
     *
     * @param ypjybgbm the value for ypxx_backup.YPJYBGBM
     *
     * @mbggenerated
     */
    public void setYpjybgbm(String ypjybgbm) {
        this.ypjybgbm = ypjybgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.YPJYBGYXQ
     *
     * @return the value of ypxx_backup.YPJYBGYXQ
     *
     * @mbggenerated
     */
    public Date getYpjybgyxq() {
        return ypjybgyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.YPJYBGYXQ
     *
     * @param ypjybgyxq the value for ypxx_backup.YPJYBGYXQ
     *
     * @mbggenerated
     */
    public void setYpjybgyxq(Date ypjybgyxq) {
        this.ypjybgyxq = ypjybgyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.JYZT
     *
     * @return the value of ypxx_backup.JYZT
     *
     * @mbggenerated
     */
    public String getJyzt() {
        return jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.JYZT
     *
     * @param jyzt the value for ypxx_backup.JYZT
     *
     * @mbggenerated
     */
    public void setJyzt(String jyzt) {
        this.jyzt = jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.VCHAR1
     *
     * @return the value of ypxx_backup.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.VCHAR1
     *
     * @param vchar1 the value for ypxx_backup.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.VCHAR2
     *
     * @return the value of ypxx_backup.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.VCHAR2
     *
     * @param vchar2 the value for ypxx_backup.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.VCHAR3
     *
     * @return the value of ypxx_backup.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.VCHAR3
     *
     * @param vchar3 the value for ypxx_backup.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.DW
     *
     * @return the value of ypxx_backup.DW
     *
     * @mbggenerated
     */
    public String getDw() {
        return dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.DW
     *
     * @param dw the value for ypxx_backup.DW
     *
     * @mbggenerated
     */
    public void setDw(String dw) {
        this.dw = dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.MC
     *
     * @return the value of ypxx_backup.MC
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.MC
     *
     * @param mc the value for ypxx_backup.MC
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.JX
     *
     * @return the value of ypxx_backup.JX
     *
     * @mbggenerated
     */
    public String getJx() {
        return jx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.JX
     *
     * @param jx the value for ypxx_backup.JX
     *
     * @mbggenerated
     */
    public void setJx(String jx) {
        this.jx = jx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.GG
     *
     * @return the value of ypxx_backup.GG
     *
     * @mbggenerated
     */
    public String getGg() {
        return gg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.GG
     *
     * @param gg the value for ypxx_backup.GG
     *
     * @mbggenerated
     */
    public void setGg(String gg) {
        this.gg = gg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.ZHXS
     *
     * @return the value of ypxx_backup.ZHXS
     *
     * @mbggenerated
     */
    public String getZhxs() {
        return zhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.ZHXS
     *
     * @param zhxs the value for ypxx_backup.ZHXS
     *
     * @mbggenerated
     */
    public void setZhxs(String zhxs) {
        this.zhxs = zhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.PINYIN
     *
     * @return the value of ypxx_backup.PINYIN
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.PINYIN
     *
     * @param pinyin the value for ypxx_backup.PINYIN
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypxx_backup.LB
     *
     * @return the value of ypxx_backup.LB
     *
     * @mbggenerated
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypxx_backup.LB
     *
     * @param lb the value for ypxx_backup.LB
     *
     * @mbggenerated
     */
    public void setLb(String lb) {
        this.lb = lb;
    }
}