package cn.edu.hist.model;

public class Yycgdmx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.YYCGDID
     *
     * @mbggenerated
     */
    private String yycgdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.YPXXID
     *
     * @mbggenerated
     */
    private String ypxxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.USERGYSID
     *
     * @mbggenerated
     */
    private String usergysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.ZBJG
     *
     * @mbggenerated
     */
    private Float zbjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.JYJG
     *
     * @mbggenerated
     */
    private Float jyjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.CGL
     *
     * @mbggenerated
     */
    private Integer cgl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.CGJE
     *
     * @mbggenerated
     */
    private Float cgje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.CGZT
     *
     * @mbggenerated
     */
    private String cgzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.VCHAR4
     *
     * @mbggenerated
     */
    private String vchar4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yycgdmx.VCHAR5
     *
     * @mbggenerated
     */
    private String vchar5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.ID
     *
     * @return the value of yycgdmx.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.ID
     *
     * @param id the value for yycgdmx.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.YYCGDID
     *
     * @return the value of yycgdmx.YYCGDID
     *
     * @mbggenerated
     */
    public String getYycgdid() {
        return yycgdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.YYCGDID
     *
     * @param yycgdid the value for yycgdmx.YYCGDID
     *
     * @mbggenerated
     */
    public void setYycgdid(String yycgdid) {
        this.yycgdid = yycgdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.YPXXID
     *
     * @return the value of yycgdmx.YPXXID
     *
     * @mbggenerated
     */
    public String getYpxxid() {
        return ypxxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.YPXXID
     *
     * @param ypxxid the value for yycgdmx.YPXXID
     *
     * @mbggenerated
     */
    public void setYpxxid(String ypxxid) {
        this.ypxxid = ypxxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.USERGYSID
     *
     * @return the value of yycgdmx.USERGYSID
     *
     * @mbggenerated
     */
    public String getUsergysid() {
        return usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.USERGYSID
     *
     * @param usergysid the value for yycgdmx.USERGYSID
     *
     * @mbggenerated
     */
    public void setUsergysid(String usergysid) {
        this.usergysid = usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.ZBJG
     *
     * @return the value of yycgdmx.ZBJG
     *
     * @mbggenerated
     */
    public Float getZbjg() {
        return zbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.ZBJG
     *
     * @param zbjg the value for yycgdmx.ZBJG
     *
     * @mbggenerated
     */
    public void setZbjg(Float zbjg) {
        this.zbjg = zbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.JYJG
     *
     * @return the value of yycgdmx.JYJG
     *
     * @mbggenerated
     */
    public Float getJyjg() {
        return jyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.JYJG
     *
     * @param jyjg the value for yycgdmx.JYJG
     *
     * @mbggenerated
     */
    public void setJyjg(Float jyjg) {
        this.jyjg = jyjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.CGL
     *
     * @return the value of yycgdmx.CGL
     *
     * @mbggenerated
     */
    public Integer getCgl() {
        return cgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.CGL
     *
     * @param cgl the value for yycgdmx.CGL
     *
     * @mbggenerated
     */
    public void setCgl(Integer cgl) {
        this.cgl = cgl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.CGJE
     *
     * @return the value of yycgdmx.CGJE
     *
     * @mbggenerated
     */
    public Float getCgje() {
        return cgje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.CGJE
     *
     * @param cgje the value for yycgdmx.CGJE
     *
     * @mbggenerated
     */
    public void setCgje(Float cgje) {
        this.cgje = cgje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.CGZT
     *
     * @return the value of yycgdmx.CGZT
     *
     * @mbggenerated
     */
    public String getCgzt() {
        return cgzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.CGZT
     *
     * @param cgzt the value for yycgdmx.CGZT
     *
     * @mbggenerated
     */
    public void setCgzt(String cgzt) {
        this.cgzt = cgzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.VCHAR1
     *
     * @return the value of yycgdmx.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.VCHAR1
     *
     * @param vchar1 the value for yycgdmx.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.VCHAR2
     *
     * @return the value of yycgdmx.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.VCHAR2
     *
     * @param vchar2 the value for yycgdmx.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.VCHAR3
     *
     * @return the value of yycgdmx.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.VCHAR3
     *
     * @param vchar3 the value for yycgdmx.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.VCHAR4
     *
     * @return the value of yycgdmx.VCHAR4
     *
     * @mbggenerated
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.VCHAR4
     *
     * @param vchar4 the value for yycgdmx.VCHAR4
     *
     * @mbggenerated
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yycgdmx.VCHAR5
     *
     * @return the value of yycgdmx.VCHAR5
     *
     * @mbggenerated
     */
    public String getVchar5() {
        return vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yycgdmx.VCHAR5
     *
     * @param vchar5 the value for yycgdmx.VCHAR5
     *
     * @mbggenerated
     */
    public void setVchar5(String vchar5) {
        this.vchar5 = vchar5;
    }
}