package cn.edu.hist.model;

public class Yyypml {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyypml.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyypml.USERYYID
     *
     * @mbggenerated
     */
    private String useryyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyypml.YPXXID
     *
     * @mbggenerated
     */
    private String ypxxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyypml.USERGYSID
     *
     * @mbggenerated
     */
    private String usergysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyypml.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyypml.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyypml.ID
     *
     * @return the value of yyypml.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyypml.ID
     *
     * @param id the value for yyypml.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyypml.USERYYID
     *
     * @return the value of yyypml.USERYYID
     *
     * @mbggenerated
     */
    public String getUseryyid() {
        return useryyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyypml.USERYYID
     *
     * @param useryyid the value for yyypml.USERYYID
     *
     * @mbggenerated
     */
    public void setUseryyid(String useryyid) {
        this.useryyid = useryyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyypml.YPXXID
     *
     * @return the value of yyypml.YPXXID
     *
     * @mbggenerated
     */
    public String getYpxxid() {
        return ypxxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyypml.YPXXID
     *
     * @param ypxxid the value for yyypml.YPXXID
     *
     * @mbggenerated
     */
    public void setYpxxid(String ypxxid) {
        this.ypxxid = ypxxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyypml.USERGYSID
     *
     * @return the value of yyypml.USERGYSID
     *
     * @mbggenerated
     */
    public String getUsergysid() {
        return usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyypml.USERGYSID
     *
     * @param usergysid the value for yyypml.USERGYSID
     *
     * @mbggenerated
     */
    public void setUsergysid(String usergysid) {
        this.usergysid = usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyypml.VCHAR1
     *
     * @return the value of yyypml.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyypml.VCHAR1
     *
     * @param vchar1 the value for yyypml.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyypml.VCHAR2
     *
     * @return the value of yyypml.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyypml.VCHAR2
     *
     * @param vchar2 the value for yyypml.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }
}